### ISSUE TITLE
Panel with 4 buttons to large

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#115]
A lot of space is taken by the left sub-panel in the result panel.
I suggest:
- run more iteration -> continue
- load as input -> restart
- load as input with last image -> set as init image?
- save files

we can move `modify image` in this panel

**Comment by buthanoid** [comment]
Also the panel could be made "horizontal" to take less space. 
"set as init image" -> don't this bring confusion between a simple "image" and a "result" which have also data tables and parameters to be added to the input panel ? maybe "set as input" ?

**Comment by bourgesl** [comment]
Maybe the panel orientation should be changed: LEFT / RIGHT => TOP / BOTTOM, so buttons could be placed on top or below, no more on the left side.

**Comment by FerreolS** [comment]
> Maybe the panel orientation should be changed: LEFT / RIGHT => TOP / BOTTOM, so buttons could be placed on top or below, no more on the left side.

good idea

**Comment by FerreolS** [comment]
load as input with last image -> update parameters ?

**Comment by buthanoid** [comment]
I move the panel and renamed the buttons. It is way better.

About the "Modify Image" button (and also the "Set as Init image" button), I personally think they are in the good place, since they are directly to the right of the list of selection of images. So every image action is at the same place. The action panel actually contains actions that are related to the full OIFitsFile and not only the image.
What do you think ? The PR is not merged yet, it can be done.
