### ISSUE TITLE
Input panel

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#21]
Separate issue for the design of the input panel of #14

**Comment by buthanoid** [comment]
Tabbed Panes can be used https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html
I think it allows to share the ViewerPanel between the Input and Result panels.
I would keep the MainPanel class and avoid creating an InputPanel class, I would just use a JPanel field for the input panel.

**Comment by buthanoid** [comment]
Started to work on https://github.com/buthanoid/oimaging/tree/input-results-panels

**Comment by bourgesl** [comment]
Did you use 2 ViewerPanel or could you make a refactoring to have ViewerPanel and ResultViewerPanel extends ViewerPanel to see if the specific aspects to handle results could be separated?

**Comment by buthanoid** [comment]
Indeed there is several points where the behaviour depend on "if it is input" so it could be refactored in two subclasses. I am waiting for more testing if we are sure to use the two tabs display

**Comment by buthanoid** [comment]
### Functional Review

The main interface is now splitted in two tabs:
- Input tab which contains the input form and the viewer of the input oifitsfile
- Results tab which contains the list of results and the viewer of the results

Some actions automatically switch tabs:
- A result of a run automatically switch to the Results tab
- In DevMode the manual adding of results automatically switch to the Results tab
- Modifying or Creating an image automatically switch to the Input tab

The actions to export and send fits now depends on the active tab. Indeed you can only export an image if you are currently displaying an image.

**Comment by buthanoid** [comment]
### Summary

#### Pull requests :next_track_button: 

The issue has the OImaging PR https://github.com/JMMC-OpenDev/oimaging/pull/64.
This issue also contains the issue https://github.com/JMMC-OpenDev/oimaging/issues/81, which fix a bug induced by the present issue, and needs the OIExplorerCore PR https://github.com/JMMC-OpenDev/oiexplorer-core/pull/9.

#### Functional Features :house: 

- split the GUI in two: input tab and results tab
- both tabs have an independent Viewer (image, oifits data, parameters, execution log)
- fix some bugs in hdu names and params (INIT_IMG...)

#### Technical Features :gear: 

- has two instances of ViewerPanel, two OCM plots at the same time
- resolve all data sharing bugs between the two ViewerPanels, for example resolve some OCM ids conflict (same filepath..)
- (en/dis)able actions depending on which tab is active
- set a clean empty state in results tab when there is no results
- use constants in ViewerPanel.jTabbedPaneVizualizations https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/5b908ffbf06e17f375ea0af083c5220f862198f9
- fix a bug, now synchronizing correctly params (INIT_IMG...) and hdu names in the loaded oifitsfile https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/961faef557a508bbad0b52380dc2224b07ba18d7
- fix a bug, no longer accumulating date suffix in renamed hduNames (when the hdu is added to the image library) https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/aa883d0d05379a32d9f403b9a69992b9531e90cc

#### Modified files :memo: 

- OImaging.java: register the switch tab action.
- MainPanel.java: two instances of ViewerPanel (and some other JPanels), tab switch listener triggers action (en/dis)abling, plots & views & subsetdef for OCM, selection of viewerPanel depending on actions and active tab, syncUI update calling display on viewers and switching tab.
- OIFitsViewPanel.java: associate a plot id instead of always using the default one, removed complete OCM reset at each plot call (only update the associated oifitsfile), handle filepath key unicity among the OCM collections and the associated oifitsfile, update the subsetdef according to the associated oifitsfile.
- ViewerPanel.java: add jTabbedPaneVizualizations constants, add a setter to showMode field, move enableActions code to MainPanel and call it because information about both ViewerPanel is needed to take the decision.
- CreateImageAction.java: use the active viewer.
- ExportFitsImageAction.java: idem.
- ExportOIFitsAction.java: idem.
- OIFitsBrowserAction.java: idem.
- ProcessImageAction.java: idem.
- SendFitsAction.java: idem.
- SendOIFitsAction.java: idem.
- SwitchTabAction.java: new file, call switch tab.
- IRModel.java: fix date suffix accumulating, fix hdu names and param synchronization.
- OImagingDocJUnitTest.java: use jTabbedPaneVizualizations constants.
- ApplicationData.xml: menu item for switch tab

**Comment by bourgesl** [comment]
Integrated
