### ISSUE TITLE
New toolbar with button

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#69]
In the result panel, there should be a toolbar with the following buttons:
- continue (rerun with the same parameters but updating the initimage)
- Change parameters (move to the input panel with the result image as init image)
- modify image (move to the input panel and modify image)
- (maybe) just move image to the input panel

**Comment by bourgesl** [comment]
Please give details on actions:
- Change parameters: change the current tab (input) + select the result image as INIT_IMG 
- just move image to the input panel ?? please clarify !

Missing action: overwrite the current input parameters with the selected result's input parameters (includes INIT_IMG...)

**Comment by FerreolS** [comment]
> Missing action: overwrite the current input parameters with the selected result's input parameters (includes INIT_IMG...)

Good point

**Comment by FerreolS** [comment]
> * Change parameters: change the current tab (input) + select the result image as INIT_IMG

That should be (IMHO): change the tab to input panel, select the result image (hdu0) as INIT_IMG and load all the INPUT PARAM of the result  as parameters in  input panel

**Comment by FerreolS** [comment]
> just move image to the input panel ?? please clarify !

change the tab to input panel, select the result image (hdu0) as INIT_IMG

**Comment by FerreolS** [comment]
it can be also, only just put the result image (hdu0) in the INIT_IMG list (what do you prefer?)

**Comment by buthanoid** [comment]
I will start to work on the toolbar on the current master branch, which do not include the "two tabs display" at the time of writing this comment. 
The actions "continue", "change parameters", "modify image" "use image as init" have meaning in the current display.

**Comment by buthanoid** [comment]
Start of work (unfinished)

- created continue action
- created IRMOdel.continue function
- this function read the selected result
- and aims to load it in the input form, in a *complete* way: targets, oi_tables, service, parameters, image hdus. 
- indeed this function could be refactored to produce a *copy OIFitsFile* function
- I chose to copy because I thought it was not safe to share the same object for the OIfitsfile of the input form and the OIFitsfile of some result, as the OIfitsfile of the input form is subject to modification.
- it is unfinished, in particular I did not copy the parameters, as it is related to the issue https://github.com/JMMC-OpenDev/oimaging/issues/71

OIMaging PR https://github.com/JMMC-OpenDev/oimaging/pull/78
OITools pr https://github.com/JMMC-OpenDev/oitools/pull/47

**Comment by buthanoid** [comment]
The following actions are to be added to OImaging:

- Change Parameters
- Continue
- Select as Init Image (maybe)

The action `Modify Image` already exists and there is already a button triggering it.
The three others actions will be associated to buttons in the toolbar (near the existing "save oifits file" button in the result tab).

#### Change Parameters Action

This action depends on the currently selected *Result* in the *Result List*.
It fills the input form with all information necessary to prepare a future run *starting from* the selected *Result*.
In particular, the *last image* will be used as *init image*. The *rgl image* is used as *rgl image*.
If there is no *last image* we can fall back to using the *init image*.
We need to select the *target*, the *software*, the *input parameters*, the *oi data*.

From the technical side, I think it would be bad to just use the *oifitsfile object of the Result*, as the *oifitsfile* associated to the *input form* is subject to updates, and the *oifitsfile object of a result* should not be modified.
Thus, we need to copy any data listed above from the *oifitsfile result object*, to the *oifitsfile* associated to the *input form*.
I think that we need a function `OiFitsFile.copy`. It could factorize some code currently in the loading of *oIfitsFiles*.

The actions ends in switching to the input tab.

#### Continue Action

I would like a precision on this action. The basic goal is to "rerun with the same parameters but with a new init image".
The *new init image* is obviously the currently displayed image in the *Results Viewer*.
I want a precision on the parameters to be "rerun". There is two possibilities:

1. We rerun what is currently in the input form, whatever it is. We just change the init image.
2. We rerun the run associated to the changed init image.

Note that the currently displayed image may have nothing to do with the last run. Indeed the user can walk and select any result in the result list.
In the case 2, `Continue Action` is just `Change Parameters` without a switch to the input form, and with an automatic trigger of `Run`.

Also should we keep on Results tab or switch on Input Tab ?

#### Set as Init Image Action

Use the currently displayed image as Init Image in the input form (and move to input tab).

**Comment by bourgesl** [comment]
I quickly tested your branch toolbar-4 and I think there is a functionnal problem: selecting a result as an input (continue or select as input) implies the initial input file is lost, no way to retrieve it again in the GUI as the initial starting point. 

I think a real swing toolbar should be used (like OIFitsExplorer has a toolbar on the top left):
https://docs.oracle.com/javase/tutorial/uiswing/components/toolbar.html

**Comment by buthanoid** [comment]
About "Select as input" it is the intended behaviour since the goal is to fill the input form, so indeed we lost the previous value of the input form.
About "More iterations" it is indeed not so clear, should it modify the input form or not ? 
- it should not: because we don't even go to the input tab, and the user clearly has no power of modifying any parameter
- it should: because during the run, the user is free to go to the input tab, click on "cancel" or read what has been used as input. I think this is a strong argument: untouched, the input form should reflect what has been sent as a Run. 

Anyway, at the end of the run, the input form will be modified with the result of the run, following the defined behaviour of Run.
