### ISSUE TITLE
Handle OImaging GUI keywords

### ISSUE THREAD

**Issue by bourgesl** [JMMC-OpenDev/oimaging#7]
Several fields in ServiceResult must be persisted as GUI keywords (non standard) in the ImageOiOutputParam table:
- ID (new field)
- start/end time
- rating
- comments
- algorithm (<=> service name)

Note: a FITS keyword is limited to 70 chars => comments will be truncated if longer !

As the class ImageOiInputParam has already an API to handle specific keywords (oimaging software), this API could be generalized in an intermediate class ImageOiParamTable to share the code between ImageOiInputParam and ImageOiOutputParam.

Finally, OImaging should explicit define GUI keywords in IRModel.addServiceResult() by calling a new method postProcess(ServiceResult) to define values for these keywords (ServiceResult values set to keywords)

**Comment by buthanoid** [comment]
For OITools part, the draft is here : [https://github.com/buthanoid/oitools/tree/new-output-keywords-2](https://github.com/buthanoid/oitools/tree/new-output-keywords-2)

For OImaging part, the draft is here : [https://github.com/buthanoid/oimaging/tree/new-output-keywords](https://github.com/buthanoid/oimaging/tree/new-output-keywords)

The moto was to keep the code taken from ImageOiInputParam and put inside abstract common ImageOiParam class, to avoid introducing of bugs.
Some part that maybe could be improved is the protected KEYWORD_METAS field, updated statically in subclasses, and its call in the constructor of ImageOiParam. 
I keeped the name to avoid bugs but some names could actually be more clear. KEYWORD_METAS for example, is not very acute since it is not the only collection of KeywordMetas in this class.

What remains in the two subclasses are the static definitions of KeywordMetas, the static adding of them to static field KEYWORD_METAS, the call to setExtName in the constructor, and the getter/setters specifics to the static keywordsMetas of the subclass.

RATING is now a "specific" OutputParam. It is not default since the defaults keywords are the parents ones, and the ones added statically by ImageOIOutputParam. For input params, specific keywords are added to the panels. For the output, no behaviour is defined yet. I think it is correct to keep things as they are, even if maybe a collection called "OImagingKeywords" or some other name would be more strict.

I saw your suggestion for naming the abstract class "ImageOiParamTable" too late so it is called "ImageOIParam" at this point.

I removed the automatic writing after each cell edit.

**Comment by bourgesl** [comment]
Looks almost good !
You pointed KEYWORD_METAS is problematic : 
- bad name (should be tableOwnKeywords ?)
- it is static ! so its content is now shared between Input & Output params !

I suggest to give this map in the ImageOIParam constructor using a static method to construct it:
super(createTableOwnKeywords()) where createTableOwnKeywords() is a private static method in each child table (Input and Output). 
This new ownTableKeyword field is no private and not static in the ImageOIParam.

**Comment by buthanoid** [comment]
Updated.

**Comment by buthanoid** [comment]
As startDate and endDate live outside the OIFitsFile (startDate is defined even before the OIFitsFile is filled by the algorithm),
I am thinking of letting them in ServiceResult, but also post-process them in keywords after the run. Thus, they will be exported, and they can be recovered during file import.

**Comment by bourgesl** [comment]
Yes start/end times are in fact java Date so String <=> Date conversion should be explicit as keywords only support numeric or String types (for now).
Let's see how to handle fields <=> keywords in both directions: postProcessing(result) and load(result)...

**Comment by buthanoid** [comment]
Updated.
Put a SimpleFormatDate in ImageOIParam.java. The format choosen can be changed. 
Maybe should define a recovery procedure when the date found in keyword does not respect the format chosen (a try my best procedure).
The parsing occurs in DevMode.craftServiceResult since this is the current only place where we load an OIFitsFile and put create a ServiceResult from it.
The formatting occurs in IRModel.postProcessOIFitsFile (which may be renamed postProcessServiceResult now ?)
Note that the formatting uses setKeywordDefault, so that the keyword value is only replaced if it was undefined. So the formatting occurs for a ServiceResult from a Run action, but not for a ServiceResult from a craftServiceResult (provided it loaded a complete oifitsfile with date keywords filled).

**Comment by bourgesl** [comment]
Let's start Pull requests to fix minor details:
- oitools: 
stdImgOIInputKeywords => IMAGE_OI_INPUT_STD_KEYWORDS (static = constant = upper case)
stdImgOIOuputKeywords => IMAGE_OI_OUTPUT_STD_KEYWORDS (static = constant = upper case)

Please add ID, comments & algorithm fields as keywords too to get the complete problem.

**Comment by buthanoid** [comment]
Note : the max size for comments is 68 if you store the string in fits formats (with the surrounding ' chars)

**Comment by buthanoid** [comment]
https://github.com/JMMC-OpenDev/oimaging/pull/9
https://github.com/JMMC-OpenDev/oitools/pull/41

**Comment by bourgesl** [comment]
Review done, I just have few questions about the date fields: 
it is not clear to me how to simplify the code as both ServiceResult start/end fields and their corresponding keywords are present and how to keep both in sync ? 
when should we use fields or keywords ?

**Comment by bourgesl** [comment]
PR #9 integrated
