### ISSUE TITLE
Remove OUT_PARAM table from input files

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#71]
To prevent ambiguities we should destroy OUT_PARAM when moving/loading an image in the input panel

**Comment by buthanoid** [comment]
Proposal: https://github.com/JMMC-OpenDev/oimaging/pull/76

reset all keywords and header cards from OITOOLS FItsHDU, it is called when an OIfitsFile is loaded in the input form.

**Comment by bourgesl** [comment]
I do not like this solution:
- table structure is corrupted (no keywords), but still written ? 
- I suspect it will make an invalid FITS file ?
I propose to check all ImageOiData.getOutputParam() usages (12 occurences in 3 projects) to check for null output table when needed with the following new methods:
- ImageOiData.getExistingOutputParam() { return outputParam; } // may be null
- ImageOiData.getOutputParam() will lazy create the table:
`if (outputParam == null) { outputParam = new ImageOiOutputParam(); }`

It will be more explicit that the output params table will not be created by default, only loaded or modified on results.

**Comment by buthanoid** [comment]
Problem is that when a Run completes, the oifitsfile of the serviceResult is used for the input form. Then it has a lot of output parameters already: outputParam will not be null.

**Comment by bourgesl** [comment]
I do not understand as the input should not be altered by any result !
If really needed (to be clarified), I would prefer removing the output params table from the input oifits structure.

**Comment by bourgesl** [comment]
Is it related to the new GUI design ?

**Comment by buthanoid** [comment]
I think there is a quiproquo on the issue.
This issue reside in the process of getting a new result, and filling the input form with some parts of the result, so the user can "resume" the computation. This is already present in OImaging, see IRModel l.184:
```java
    private void loadOIFits(final OIFitsFile oifitsFile) {
        // change current model immediately:
        this.oifitsFile = oifitsFile;
```
The goal of the issue was to prevent output params to be inserted in the input form. The reason is that it can be confusing for the user. Even if they are not used, and they do not interfere with the computation, the user could think that they are used.

I first thought of removing or nullify the outputParams but it is a final field, also a lot of methods call it. Then I thought it safer to just empty the lists, but you said it was maybe unsafe too. Now I think of just hiding the output params in the GUI, but the output params will still be present when we save the oifitsfile.

**Comment by bourgesl** [comment]
So this issue consists in removing the output params table (by a new `ImageOiData` API) to skip displaying it in the GUI and do not write it in saved FITS file.

I propose again to have a basic API to:
- lazily create the outputParam table in `ImageOiData.getOutputParam()`
- add `ImageOiData.getExistingOutputParam() { return outputParam; }`
- remove the table by `ImageOiData.removeOutputParam() { outputParam = null; }`
- fix existing usages of `ImageOiData.getOutputParam()`  to use `ImageOiData.getExistingOutputParam()` when possible or add needed null checks in the remaining cases

**Comment by buthanoid** [comment]
done
associated oiexplorer pr https://github.com/JMMC-OpenDev/oiexplorer-core/pull/8
