### ISSUE TITLE
Improve Image identification in FitsImagePanel views

### ISSUE THREAD

**Issue by bourgesl** [JMMC-OpenDev/oimaging#8]
The FitsImagePanel displays a too complicated title (file name ...) from FitsImage.getFitsImageIdentifier() 
It would be better to use the HDU_NAME (or renamed by the GUI) for the image, but also indicate the associated result.

Two solutions:
- modify FitsImagePanel to have a new ID field given with the image and displayed in place or as a prefix in the chart's title
- use setFitsImageIdentifier() to define the user-defined or better identifier in the OImaging code

To be investigated as the ViewerPanel only deals with FitsImageHDU so no mean to get its ServiceResult.

**Comment by buthanoid** [comment]
In IRModel.postProcessOIFitsFile ? 
We could loop on FitsImages and call setFitsImageIdentifier.
For the label, what about composing some interesting keywords like the algorithm used, the target, the hdu (primary or initial image), and the current count of images indexes ? And not printing the file name as currently, which is too long.  
After that we can still reflect about letting the user enter a completely personalized label.

**Comment by bourgesl** [comment]
What should be displayed for input images ? ie images loaded manually not coming from results.
If keywords change, like result ID, the image identifier should be updated as well...

**Comment by buthanoid** [comment]
Note : There is also different labels for images in the "Image Input list".
There is also image labels in the view panel, where you can choose which image you want to display (the input one (if any) or the result one).

**Comment by buthanoid** [comment]
Problem: 
when you click on "Run", it calls the function OIFitsWriter.writeOIFits, which himself call OIFitsWriter.createHDUnits. This last one creates HDUs from the ones found in IRModel.oifitsfile. Problem is that it calls FitsImageWriter.createImageData which always rename the image. Why ? At least in OImaging it does not serve because the file resulting from the algorithm will be loaded and its filename will be used for the image identifiers, so the filename of the input file will not appear in the result. 
Also this renaming, while not appearing in the result of the run, actually change the name of the initial image used. This image can be the result of a previous run, which thus get renamed, which is confusing. 
i propose to remove this renaming in FitsImageWriter, unless it is used for something

**Comment by buthanoid** [comment]
Yes what you described is what I meant, -3 modify -2.
I agree with the constant flag, it seems the safest since the `writeOIFits` functions is called in different situations : `TestMergeUtils.merge`, `WriteOIFitsTest.writeLoadCompare`, `ViewerPanel.exportOIFits`..
And the `fitsImageIdentifier` is also used in different situations.
We only know that in this specific situation it will be harmless to not update the identifier with the name of the temporary file

**Comment by buthanoid** [comment]
https://github.com/JMMC-OpenDev/oimaging/pull/34
https://github.com/JMMC-OpenDev/oitools/pull/43
